Booking/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from booking_app.views import BookingView, PriceListView, AddClientView, AddTreatmentView, ClientLoginView, BaseView, \
    BookingDetailView, BookingsListView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', BaseView.as_view(), name="base"),
    url(r'^home$', PriceListView.as_view(), name="home"),
    url(r'^booking/(?P<treatment_id>(\d)+)', BookingView.as_view(), name="booking"),
    url(r'^add_client$', AddClientView.as_view(), name="add_client"),
    url(r'^user_login$', ClientLoginView.as_view(), name="user_login"),
    url(r'^add_treatment$', AddTreatmentView.as_view(), name="add_treatment"),
    url(r'^home$', PriceListView.as_view(), name="home"),
    url(r'^login/$', auth_views.login, {'template_name': 'base.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),

    url(r'^apibookings/', BookingsListView.as_view()),
    url(r'^apibooking/(?P<pk>[0-9]+)/$', BookingDetailView.as_view()),

]

booking_app/forms.py
from django.contrib.auth.models import User

from booking_app.models import Treatment, Booking
from django import forms
import re
from bootstrap_datepicker.widgets import DatePicker


class AddClientForm(forms.Form):
    first_name= forms.CharField(label="imię",max_length=64)
    last_name= forms.CharField(label="nazwisko",max_length=64)
    password = forms.CharField(label="hasło", widget=forms.PasswordInput)
    repeat_password = forms.CharField(label="powtórz hasło", widget=forms.PasswordInput)
    username = forms.IntegerField(label="nr telefonu")

    def clean_username(self):
        number = str(self.cleaned_data['username'])
        number = re.sub(r"\D", "", number)
        pattern = r"^\d{9}$"
        if not re.match(pattern, number):
            raise forms.ValidationError("Podaj poprawny numer")
        return number


class AddTreatmentForm(forms.ModelForm):
    class Meta:
        model = Treatment
        fields = "__all__"


class ClientLoginForm(forms.Form):
    username = forms.IntegerField(label="nr telefonu")
    password = forms.CharField(label="hasło", widget=forms.PasswordInput)


class BookingForm(forms.Form):

    date = forms.DateField(widget=DatePicker(
            options={
                "maxViewMode": 0,
                "todayBtn": True,
                "language": "pl-PL",
                "daysOfWeekDisabled": "0,7",
                "daysOfWeekHighlighted": "1,2,3,4,5,6",
                "calendarWeeks": True,
                "todayHighlight": True,
                "format": "yyyy-mm-dd",
                "autoclose": True,
            }
        ))
    time = forms.TimeField(widget=forms.Select)


# "YYYY-MM-DD HH:mm",



"""
 
 # number= filter(lambda x: x.isdigit(), number)
"""

templates/add_client.html
{% extends "base.html" %}

{% block content %}{% endblock %}

{% block banner %}

    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="zarejestruj">
    </form>
{{ message }}
{% endblock %}

templates/add_treatment.html
{% extends "base.html" %}


{% block content %}{% endblock %}

{% block banner %}
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Dodaj">
    </form>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
      {% block head %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'assets/ico/favicon.ico'%}">

    <title>Company</title>

    <!-- CSS Plugins -->
    <link rel="stylesheet" href="{% static 'assets/plugins/ionicons/css/ionicons.min.css'%}">

    <!-- CSS Global -->
    <link rel="stylesheet" href="{% static 'assets/css/theme.css'%}">
    {% endblock %}
  </head>


  <body data-spy="scroll" data-target="#navbar_main" data-offset="80">
  {% block content %}

    <!-- PRELOADER
    ================================================== -->
    <div class="preloader">
      <img src="{% static 'assets/img/spinner.svg" alt="Loading..." class="preloader__spinner'%}">
    </div>

    <!-- NAVBAR
    ================================================== -->
    <nav class="navbar navbar-fixed-top navbar-default">
      <div class="container">

        <!-- Brand name -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar_main" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbar_main">

          <ul class="nav navbar-nav navbar-right">
            <li class="active">
              <a href="/home">Home</a>
            </li>
            <li><a href="/add_client">Zarejestruj</a></li>
            <li><a href="/add_treatment">Dodaj zabieg</a></li>
            <li><a href="/user_login">Zaloguj</a></li>
            <li><a href="#section_pricing">Pricing</a></li>
            <li><a href="#section_testimonials">Testimonials</a></li>
            <li><a href="#section_news">News</a></li>
            <li><a href="#section_newsletter">Sign Up</a></li>
            <li><a href="#section_contact">Contact</a></li>
          </ul>

        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
  {% endblock %}
    </nav>

    <!-- BANNER
    ================================================== -->
    {% block banner %}
    <section class="section_banner" id="section_banner">



      <!-- Images -->
      <div class="banner__carousel__img"
           data-images="{% static 'assets/img/5.jpg'%}">
      </div>

      <div class="container">
        <div class="row">
          <div class="col-sm-6">

            <h1 class="page-header text-white text-left animate-down animate-xs-step-0">
              UMÓW SIĘ  <br>
              NA WIZYTĘ W <span>Day Spa</span>
            </h1>
            <p class="page-subheader text-white-muted text-left animate-down animate-xs-step-1">
              Rozpal  swoje zmysły i zrelaksuj się w najlepszym DAY SPA w Poznaniu. Wielokrotnie wyróżniany prestiżowymi nagrodami DAY SPA to 1000m2 relaksu w luksusowych warunkach oraz kompleksowej dbałości o zdrowie i urodę.
            </p>
            <div class="text-left">
              <a href="#section_services" class="btn btn-primary animate-down animate-xs-step-2">
                Find out more
              </a>
            </div>

          </div>

          <div class="col-sm-6 col-lg-4 col-lg-offset-1">

            <div class="banner__form">

              <h3 class="page-header">
                ZALOGUJ
              </h3>
                                  {{ form.errors }}
                <form method="post">
                {% csrf_token %}
                    <div class="form-group">
                  <label for="name_1">NUMER TELEFONU</label>
                    <input type="text" name="username" class="form-control">
                </div>
                <div class="form-group">
                  <label for="email_1">HASŁO</label>
                  <input type="password" name="password" class="form-control">
                </div>
                <button class="btn btn-block btn-primary">ZALOGUJ</button>
              </form>
            </div> <!-- / .banner__form -->

          </div>
        </div> <!-- / .row -->
      </div> <!-- / .container -->

    </section>
    {% endblock %}
     <!-- FOOTER
    ================================================== -->
        {% block footer %}
    <footer class="section_footer">

      <div class="container">
        <div class="row">
          <div class="col-sm-9">

            <p class="footer__copyright">
              <span id="footer__year">2017</span> &copy; Wolfram theme by <a href="http://simpleqode.com" target="_blank">Simpleqode.com</a> | Purchase via <a href="https://wrapbootstrap.com/theme/wolfram-multipurpose-one-page-template-WB0915821" target="_blank">Wrapbootstrap.com</a>
            </p>

          </div>
          <div class="col-sm-3">

            <ul class="footer__social">
              <li>
                <a class="twitter" href="#">
                  <i class="ion-social-twitter"></i>
                </a>
              </li>
              <li>
                <a class="facebook" href="#">
                  <i class="ion-social-facebook"></i>
                </a>
              </li>
              <li>
                <a class="pinterest" href="#">
                  <i class="ion-social-pinterest"></i>
                </a>
              </li>
            </ul>

          </div>
        </div> <!-- / .row -->
      </div> <!-- / .container -->
        {% endblock %}
    </footer>

    <!-- JAVASCRIPT
    ================================================== -->

    <!-- JS Global -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js'%}"></script>

    <!-- JS Plugins -->
    <script src="{% static 'assets/plugins/smoothscroll/smoothscroll.min.js'%}"></script>
    <script src="{% static 'assets/plugins/backstretch/jquery.backstretch.min.js'%}"></script>
    <script src="{% static 'assets/plugins/contact-form/contact.js'%}"></script>
    <script src="{% static 'assets/plugins/waypoints/jquery.waypoints.min.js'%}"></script>

    <!-- JS Custom -->
    <script src="{% static 'assets/js/theme.js'%}"></script>
    <script src="{% static 'assets/js/custom.js'%}"></script>

  </body>
</html>

templates/base1.html
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">

    <title>Datepicker for Bootstrap</title>

    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>

    <link id="bs-css" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">

    <link id="bsdp-css" href="{% static 'contrib/bootstrap-datepicker3.min.css' %}" rel="stylesheet">




    <script src="{% static 'contrib/bootstrap-datepicker.min.js' %}"> </script>

    <script src="{% static 'contrib/bootstrap-datepicker/bootstrap-datepicker.pl.min.js' %}" charset="UTF-8"></script>



</head>




<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <div id="footer">
        <span>{% block footer %}{% endblock %}</span>
    </div>
</body>
</html>

templates/booking.html
{% load static %}
{% load bootstrap %}

    <title>Umów wizytę</title>

    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <link id="bs-css" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <link id="bsdp-css" href="{% static 'contrib/bootstrap-datepicker3.min.css' %}" rel="stylesheet">
    <script src="{% static 'contrib/bootstrap-datepicker.min.js' %}"> </script>
    <script src="{% static 'contrib/bootstrap-datepicker/bootstrap-datepicker.pl.min.js' %}" charset="UTF-8"></script>


{#<script>#}
{#$(document).ready(function() {#}
{#    $('.datepicker').datepicker();});#}
{#</script>#}

{##}
{#<html>#}
{#<body>#}
{##}
{#<ul id="myList">#}
{#  <li>Coffee</li>#}
{#  <li>Tea</li>#}
{#</ul>#}
{##}
{#<p>Click the button get the HTML content of the ul element.</p>#}
{##}
{#<button onclick="myFunction()">Try it</button>#}
{##}
{#<p id="demo"></p>#}
{##}
{#<script>#}
{#function myFunction() {#}
{#    var x = document.getElementById("myList").innerHTML;#}
{#    document.getElementById("demo").innerHTML = x}#}
{#</script>#}
{##}
{#</body>#}
{#</html>#}


{#connecting bootstrap datepicker with django form:#}

   <form action="" method="post">

      {{ form|bootstrap}}
      {% csrf_token %}


    </form>

<body>

        <div id="time_">
            <select>
                <option>" "</option>
            </select>
        </div>

</body>

  <script>
    $("#id_date").change(function () {
        var date_ = $(this).val();

        $.get("http://127.0.0.1:8000/apibookings/booking?date=" + date_, function (data) {
            console.log("pobrałam:", data);
            var select = $('<select>');
            for (var i = 0; i < data.length; i++) {
                var d = data[i];
                console.log("DATA ", i, d);

                var option = $('<option>');
                option.text(d.time);

                select.append(option);
            }

            var time_ =  $("#time_");
            time_.html( select );
{#             time.append(select);#}
{#            time_.html( "<select>select.text()</select> ");#}


            console.log("KONIEC");
            alert("Load was performed.");
        })
    });

</script>







{#$('#datetimepicker').data("DateTimePicker").FUNCTION()#}



{#<script>#}
{#var u = "http://127.0.0.1:8000/apibookings/";#}
{##}
{#$.get(u , function(data) {#}
{#	//pobralismy listę filmów#}
{#	console.log("POBRAŁEM i zamieniłem na obiekt(y):", data);#}
{##}
{#	//biegamy po filmach, dla każdego budujemy instancję DOM#}
{#	//i doklejamy do #myMovieList#}
{#	var select = $('<select>');#}
{#	for(var i=0; i<data.length; i++) {#}
{#		var d = data[i];#}
{#		console.log("DATA ", i,  d)#}
{##}
{#		var option = $('<option>');#}
{#		option.text(d.time);#}
{#		option.text(d.time + ' / ' + d.date);#}
{##}
{#		select.append(option);#}
{#	}#}
{##}
{#  $("#time_").append( select );#}
{##}
{#  console.log("KONIEC");#}
{#  alert( "Load was performed." );});#}
{##}
{##}
{#</script>#}

templates/booking1.html
<!DOCTYPE html>
<html>
<head>
	<title>Test API</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
<script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
</head>
<body>

<div id="time_">

</div>


<script>
var u = "http://127.0.0.1:8000/bookings/";

$.get(u , function(data) {
	//pobralismy listę filmów
	console.log("POBRAŁEM i zamieniłem na obiekt(y):", data);

	//biegamy po filmach, dla każdego budujemy instancję DOM
	//i doklejamy do #myMovieList
	var select = $('<select>');
	for(var i=0; i<data.length; i++) {
		var d = data[i];
		console.log("DATA ", i,  d)

		var option = $('<option>');
		option.text(d.time + ' / ' + d.date);

		select.append(option);
	}

  $("#time_").append( select );

  console.log("KONIEC");
  alert( "Load was performed." );
});


</script>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}{% endblock %}
{% block banner %}
  {% for treatment in price_list %}
     <a href="/booking/{{ treatment.id }}">{{ treatment.name }}</a>
      {{ treatment.price}}<br>
  {% endfor%}


{% csrf_token %}

{% endblock %}

templates/user_login.html
{% extends "base.html" %}

{% block content %}





{% endblock %}
{% block banner %}
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="zaloguj">
    </form>
{{ message }}
{% endblock %}